### ISSUE TITLE
Rename project script not working

### ISSUE THREAD

**Issue by denny351** [react-native-market/firebase-authentication-kit#29]
Fresh project and all I did was install dependencies. I am on Node.js v12.14.0, but also tried with v10.

```
MacBook-Pro:rnm-firebase-authentication-kit-0.0.2 macuser$ yarn rename-project
yarn run v1.21.1
$ node scripts/rename.js
---------------------------------------------------------
Enter your Project name, e.g. My New Project: Test Project
---------------------------------------------------------
Enter your Company name, e.g. My Company: Test Company
---------------------------------------------------------
---------------------------------------
Updating package name: com.testcompany.testproject
---------------------------------------
[replaceInFile] Error occurred:  [Error: ENFILE: file table overflow, open './ios/Pods/boost-for-react-native/boost/numeric/odeint/algebra/detail/for_each.hpp'] {
  errno: -23,
  code: 'ENFILE',
  syscall: 'open',
  path: './ios/Pods/boost-for-react-native/boost/numeric/odeint/algebra/detail/for_each.hpp'
}
---------------------------------------
Finished updating package name
---------------------------------------

---------------------------------------
Updating project name: TestProject
---------------------------------------
glob error [Error: EMFILE: too many open files, scandir '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/android'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/android'
}
[replaceInFile] Error occurred:  [Error: EMFILE: too many open files, scandir '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/android'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/android'
}
glob error [Error: EMFILE: too many open files, scandir '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/ios'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/ios'
}
[replaceInFile] Error occurred:  Error: No files match the pattern: ./ios/**
    at /Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/replace-in-file/lib/helpers/glob-async.js:27:23
    at f (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:210:5)
    at Glob._finish (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/glob/glob.js:197:8)
    at done (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/glob/glob.js:637:12)
    at /Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/glob/glob.js:626:10
    at RES (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/inflight/inflight.js:31:16)
    at f (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/node_modules/once/once.js:25:25)
---------------------------------------
Finished updating project name
---------------------------------------

---------------------------------------
Rename project files
---------------------------------------
(node:39305) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, scandir './'
    at Object.readdirSync (fs.js:854:3)
    at renameFiles (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/scripts/rename.js:56:20)
    at /Users/macuser/rnm-firebase-authentication-kit-0.0.2/scripts/rename.js:108:5
    at new Promise (<anonymous>)
    at renameProjectFiles (/Users/macuser/rnm-firebase-authentication-kit-0.0.2/scripts/rename.js:107:10)
    at /Users/macuser/rnm-firebase-authentication-kit-0.0.2/scripts/rename.js:188:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:39305) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
glob error [Error: EMFILE: too many open files, scandir '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/src'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/src'
}
glob error [Error: EMFILE: too many open files, scandir '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/android'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/Users/macuser/rnm-firebase-authentication-kit-0.0.2/android'
}
✨  Done in 10.12s.
```

**Comment by robbiew** [comment]
Looks like there is a solution to this (not 100% sure if this is correct because I had to search the Internet and search closed issues?):
- run "npm rename-project" before installing pods (docs are in error)

Love this product, but there are quite a few issues with this that could be avoided with a timely README update...?

**Comment by ftx** [comment]
Me, i have just move the script on root folder and it's ok.
