### ISSUE TITLE
Pod Install: Cannot find module '/../rnm-firebase-authentication-kit-0.0.2/ios/undefined'

### ISSUE THREAD

**Issue by kangzeroo** [react-native-market/firebase-authentication-kit#40]
Hello react-native-market!

First time react-native developer here. I just finished setup on my other app and thought I would try out your market place pre-mades. However, I have run into an issue upon `$ pod install` step.
My purchase id is (HLWdeKixxP0NaXTN2uUQ), here are the details of my issue:

```
$ pod install

internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module '/Users/kangzeroo/Downloads/rnm-firebase-authentication-kit-0.0.2/ios/undefined'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[!] Invalid `Podfile` file: 767: unexpected token at ''.

 #  from /Users/kangzeroo/Downloads/rnm-firebase-authentication-kit-0.0.2/ios/Podfile:45
 #  -------------------------------------------
 #
 >    use_native_modules!
 #  end
 #  -------------------------------------------
```

**Comment by kangzeroo** [comment]
Hello could I please get a refund? I had to do it myself from scratch.

**Comment by kangzeroo** [comment]
Hello @Salakar @ehesp,

Could I get a refund for this? I purchased your other product Notifee.app, and it would be nice to get a refund for the above product that didn't work out. Thanks so much!

https://github.com/notifee/react-native-notifee/issues/1#issuecomment-602014482

**Comment by jacksonrdlc** [comment]
@kangzeroo did you move past this issue?

I solved it like this:

```
rm -rf node_modules && rm ./ios/Podfile.lock
yarn install
cd ios
pod install --repo-update
```
